const authentication = require('./controllers/authentication')
const songsController = require('./controllers/songController')
const authenticationPolicy = require('./policies/authenticationPolicy')
const BookmarksController = require('./controllers/bookmarksController.js')
const HistoriesController = require('./controllers/historiesController.js')
const isAuthenticated = require('./policies/isAuthenticated')

module.exports = (app) => {
  app.post('/register', authenticationPolicy.register, authentication.register)
  app.post('/login', authentication.login)
  app.get('/songs', songsController.songIndex)
  app.get('/songs/:songId', songsController.show)
  app.post('/songs', songsController.post)
  app.put('/songs/:songId', songsController.put)
  app.get('/bookmarks', isAuthenticated, BookmarksController.index)
  app.post('/bookmarks', isAuthenticated, BookmarksController.post)
  app.delete('/bookmarks/:bookmarkId', isAuthenticated, BookmarksController.delete)
  app.get('/histories', HistoriesController.index)
  app.post('/histories', HistoriesController.post)
}
